Logging
bakulevalena/library pull request #1
Opened 2019-11-27 09:59 UTC by bakulevalena

2019-11-30 17:44 UTC, Mityushin requested changes

2019-11-30 17:44 UTC, Mityushin commented on logs/app.log
> +00:26:36.355 [http-nio-8080-exec-1] ERROR [c.l.s.c.ControllerExceptionHandler] HTTP 500 returned
Удали этот файл, добавь его в .gitignore, измени последний коммит (флаг --amend), чтобы он пропал навсегда из репозитория

2019-11-30 17:44 UTC, Mityushin commented on src/main/java/com/library/storage/controller/AuthorController.java
> +        logger.debug("Time for saveAuthor {}", runTime);
В таком виде не понятно, в каких единицах измерено время

2019-11-30 17:44 UTC, Mityushin commented on src/main/java/com/library/storage/controller/AuthorController.java
> +        return author == null ? ResponseEntity.status(HttpStatus.BAD_REQUEST).body(null) : ResponseEntity.ok(author);
Тернарный оператор - плохой тон, когда выражение содержит так много символов. Переделай на if-конструкцию, либо используй Optional

2019-11-30 17:44 UTC, Mityushin commented on src/main/java/com/library/storage/job/TimeJob.java
> +    @Scheduled(fixedDelay = 10000, initialDelay = 0)
Вынеси в конфигурацию fixedDelay (в файл application.properties). initialDelay по-умолчанию = 0, явное декларирование этого параметра излишне

2019-11-30 17:44 UTC, Mityushin commented on src/main/java/com/library/storage/job/TimeJob.java
> +public class TimeJob {
Не говорящее название класса. Вызывает ассоциацию, что происходит какая-то работа со временем, но её тут нет

2019-11-30 17:44 UTC, Mityushin commented on src/main/java/com/library/storage/service/AuthorProcessingService.java
>      public String processAuthor(AuthorDTO author) {
Над методами, выполняющими операции, изменяющими состояние базы данных, крайне рекомендую аннотацию `@Transactional`, чтобы все действия внутри метода гарантированно выполнялись рамках одной транзакции

2019-11-30 17:44 UTC, Mityushin commented on src/main/java/com/library/storage/service/AuthorProcessingService.java
> +        if (allAuthors.isEmpty()) {
Предполагаю, что тут будет NPE, когда авторов в БД не окажется

2019-11-30 17:44 UTC, Mityushin commented on src/main/java/com/library/storage/service/AuthorProcessingService.java
> +            logger.warn("Unable to get the author by ID");
Логи бесполезны, если по ним нельзя исследовать проблему. Данная запись лишь укажет, что автор не был найден. Между тем, по какому именно ID автора не нашлось - не ясно. Это не пароль и не конфиденциальная информация о пользователе - смело логгируй

2019-11-30 17:44 UTC, Mityushin commented on src/main/java/com/library/storage/service/AuthorProcessingService.java
> +        logger.debug("Author is gotten");
Аналогично комменту про ID в логгах

2019-11-30 17:44 UTC, Mityushin commented on src/main/java/com/library/storage/service/AuthorProcessingService.java
> +        logger.debug("Getting the author by ID");
Аналогично комменту про ID в логгах

2019-11-30 17:44 UTC, Mityushin commented on src/main/resources/logback.xml
> +			<fileNamePattern>logs/archived/app.%d{yyyy-MM-dd}.%i.log</fileNamePattern>
относительные пути могут вызвать ситуацию, когда на поиск логов уйдёт много времени. Используй абсолютные, рекомендую Unix-стиль. Благо windows 10 умеет их переводить в свой windows-стиль. И вынеси это в параметр, который расположен где-нибудь в начале XML-файла

2019-11-30 17:44 UTC, Mityushin commented on src/main/resources/logback.xml
> +			<!-- total size of all archive files, if total size > 20GB,
удалять лучше не по размеру занимаемой памяти, а по времени. В данном случае можно использовать 30 дней

2019-11-30 19:38 UTC, bakulevalena commented on src/main/java/com/library/storage/service/AuthorProcessingService.java
> +        if (allAuthors.isEmpty()) {
почему?

2019-11-30 19:41 UTC, Mityushin commented on src/main/java/com/library/storage/service/AuthorProcessingService.java
> +        if (allAuthors.isEmpty()) {
Не уверен, что вернётся пустая коллекция, а не null

2019-12-02 20:43 UTC, Mityushin approved these changes

2019-12-02 20:43 UTC, Mityushin commented on src/main/java/com/library/storage/service/BookProcessingService.java
> +            logger.warn("Unable to get all books");
Пустая коллекция - не ошибка

2019-12-04 10:44 UTC, merged