Telegram
bakulevalena/library pull request #2
Opened 2020-01-24 23:23 UTC by bakulevalena

2020-01-26 17:53 UTC, Mityushin commented on pom.xml
> +        </dependency> -->
Подвисшие бесполезные комментарии

2020-01-26 18:00 UTC, Mityushin requested changes

2020-01-26 18:00 UTC, Mityushin commented on src/main/java/com/library/storage/config/TelegramConfig.java
> +    public String getToken() {
Используй lombok

2020-01-26 18:00 UTC, Mityushin commented on src/main/java/com/library/storage/controller/ControllerExceptionHandler.java
> +        log.error("HTTP 500 returned", e);
По такой записи в логе создаётся ощущение, что ответ 500 пришёл от внешней системы тебе в код. Нужно переименовать во что-то говорящее. Например: the error was occurred

2020-01-26 18:00 UTC, Mityushin commented on src/main/java/com/library/storage/controller/TelegramWebhookController.java
> +    public static final String BOOK_COMMAND = "/books";
почему public?

2020-01-26 18:00 UTC, Mityushin commented on src/main/java/com/library/storage/controller/TelegramWebhookController.java
> +            createResponse(message.getMessage().getChat().getId(), message.getMessage().getText(), message.getMessage().getEntities());
логика должна быть в сервисе

2020-01-26 18:00 UTC, Mityushin commented on src/main/java/com/library/storage/controller/TelegramWebhookController.java
> +            e.printStackTrace();
используй `log.warn`

2020-01-26 18:00 UTC, Mityushin commented on src/main/resources/application.yml
> +  #   connection-timeout: 20000
лишние комментарии

2020-01-26 20:57 UTC, bakulevalena commented on src/main/java/com/library/storage/controller/TelegramWebhookController.java
> +    public static final String BOOK_COMMAND = "/books";
не должно быть public, ошибка

2020-01-26 21:00 UTC, bakulevalena commented on pom.xml
> +        </dependency> -->
закомментировано то, что нужно для перехода на postgresql, пока оставим

2020-01-26 21:00 UTC, bakulevalena commented on src/main/resources/application.yml
> +  #   connection-timeout: 20000
закомментировано то, что нужно для перехода на postgresql, пока оставим [2]

2020-02-19 08:46 UTC, Mityushin approved these changes
Поправь мелкие замечания и to merge

2020-02-19 08:46 UTC, Mityushin commented on src/main/java/com/library/storage/controller/TelegramWebhookController.java
> +            telegramService.createResponse(message.getMessage().getChat().getId(), message.getMessage().getText(), message.getMessage().getEntities());
Очень длинная строка

2020-02-19 08:46 UTC, Mityushin commented on src/main/java/com/library/storage/service/TelegramService.java
> +        }
Из метода в метод копипаста try-catch, вынеси весь этот блок в отдельный метод

2020-02-19 08:46 UTC, Mityushin commented on src/main/java/com/library/storage/service/TelegramService.java
> +    public void createResponse(Long chat, String text, List<Telegram.Entity> entities) {
Не говорящее название метода

2020-03-08 12:43 UTC, merged